version: "3.8"
services:
  # express:
  #   image: balenalib/raspberry-pi-alpine-node:18.11.0-3.15
  #   working_dir: /home/node/app
  #   volumes:
  #     - ./app:/home/node/app
  #   ports:
  #     - 3000:3000
  #   command: npm run dev
  #   privilegied: true
  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0

  db:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project2
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin
    ports:
      - 8080:80

volumes:
  dbdata:
