version: "3.8"
services:
  # Node application with express server
  express:
    image: node
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    privileged: true
    ports:
      - 80:3000
    command: npm start
    restart: always
    depends_on:
      - db
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0

  # MYSQL server
  db:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project2
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  # MYSQL web management
  pma:
    image: phpmyadmin
    ports:
      - 8080:80
    restart: always

volumes:
  dbdata:
